version: '3.9'

services:

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app
    command: sh -c 'npm install && npm run start'

